blog/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,PasswordField,ValidationError,TextAreaField,SubmitField,SelectField
from wtforms.validators import Required,Email
from ..db_class import Subscribe

class blogForm(FlaskForm):
  '''
  class defining how the blog form shall look like
  '''
  category=SelectField(u'Enter Category of blog', choices =[('Lifestyle Blogs','Lifestyle Blogs'),('Entertainment Blogs','Entertainment Blogs'),('Education Blogs','Education Blogs'),('Religious Blogs','Religious Blogs'),('Political Blogs','Political Blogs'),('Fashion Blogs','Fashion Blogs')])
  title=StringField("Enter Blog's Title", validators=[Required()])
  form_body=TextAreaField('Write the blog')
  submit=SubmitField('Post')

class U_profileForm(FlaskForm):
  '''
  class defining how an update profile form shall look like
  '''
  bio=TextAreaField('Enter you Bio', validators=[Required()])
  submit=SubmitField('Submit')

class commentForm(FlaskForm):
  '''
  class that defines how the comment form shall look like
  '''
  body=TextAreaField('Enter your comment', validators=[Required()])
  submit=SubmitField('Post Comment')

class subscribeForm(FlaskForm):
  '''
  class that defines how the subscribe form shall look like
  '''
  email=StringField('Enter your email address',validators=[Required(),Email()])
  submit=SubmitField('Subscribe')  

  def validate_email(self,data_field):
    '''
    function that validates no email duplicates
    '''
    if Subscribe.query.filter_by(email=data_field.data).first():
      raise ValidationError('That Email is taken.Please use another email')

blog/__init__.py
from flask import Flask
from config import config_options
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_simplemde import SimpleMDE
from flask_mail import Mail



login_manager=LoginManager()
login_manager.session_protection='strong'
login_manager.login_view='auth.login'

db=SQLAlchemy()
bootstrap=Bootstrap()
simple=SimpleMDE()
mail=Mail()

photos=UploadSet('photos',IMAGES)


def create_app(config_name):
  '''
  function responsible for registering blueprints and instances of imports
  '''
  app=Flask(__name__)
  app.config.from_object(config_options[config_name])

  db.init_app(app)
  bootstrap.init_app(app)
  login_manager.init_app(app)
  simple.init_app(app)
  mail.init_app(app)
  
  
  
  configure_uploads(app,photos)
  

  from .auth import auth as auth_blueprint
  app.register_blueprint(auth_blueprint,url_prefix='/authenticate')

  from .main import main as main_blueprint
  app.register_blueprint(main_blueprint)

  from .request import configure_request
  configure_request(app)
  

  return app
  

blog/main/__init__.py
from flask import Blueprint
main=Blueprint('main',__name__)
from . import views,errors,forms

blog/main/views.py
from flask import render_template,redirect,url_for,request,abort
from . import main
from flask_login import login_required,current_user
from ..db_class import User,Blog,Comment,Subscribe
from .. import db,photos
from .forms import U_profileForm,blogForm,commentForm,subscribeForm
import markdown2
from ..request import get_quotes
from ..email import mail_message

@main.route('/')
def index():
  '''
  view function that renders the home page on start up
  '''
  quote=get_quotes()
  title='Blog_Site'
  return render_template('index.html', title=title,quote=quote)

@main.route('/blog/<category>')
def blog(category):
  '''
  view function that renders the blog template and displays blogs based category
  '''
  title=category
  blogs=Blog.get_blogs(category)
    
  return render_template('blog.html',blogs=blogs,title=title)

@main.route('/blog/new/blog', methods=['GET','POST'])  
@login_required
def new_blog():
  '''
  view function that renders the post blog form for adding new blogs  
  '''
  form=blogForm()
  if form.validate_on_submit():
    category=form.category.data    
    title=form.title.data
    new_body=form.form_body.data
    body_format= markdown2.markdown(new_body,extras=["code-friendly", "fenced-code-blocks"])

    new_blog=Blog(category=category,title=title,body=body_format,posted_by=current_user.username,user_id=current_user.id)
    new_blog.save_blog()
            
    # subscribers=Subscribe.get_subscribers()  

    # if subscribers is None:
      # abort(404)

    # else:
      # for sub in subscribers:        
        # mail_message("A new Blog Posted Check it out","email/new_blog",sub.email,sub=sub)


    return redirect(url_for('main.blog', category=category))

  return render_template('new_blog.html',form=form)  

@main.route('/blog/<int:id>/update', methods=['GET','POST'])  
@login_required
def update_blog(id):
  '''
  view function tha renders the update blog page indorder to update a blog
  '''
  blog_found=Blog.query.filter_by(id=id).first()    
  
  if blog_found is None:
    abort(404)

  form=blogForm()
  if form.validate_on_submit():
    blog_found.category=form.category.data
    blog_found.title=form.title.data      
    blog_found.body=markdown2.markdown(form.form_body.data,extras=["code-friendly", "fenced-code-blocks"])         
    
    db.session.add(blog_found)
    db.session.commit()

    return redirect(url_for('main.blog',category=blog_found.category))

  title="Update Blog"
  return render_template('updateblog.html',form=form,title=title)  

@main.route('/profile/<name>', methods=['GET','POST'])
def profile(name):
  '''
  view function that renders the profile page once triggered
  '''
  user=User.query.filter_by(username=name).first()
  personalblogs=Blog.personal_blogs(user.id)
  
  if user is None:
    abort(404)

  form=subscribeForm()

  if form.validate_on_submit():

    new_sub=Subscribe(email=form.email.data)

    new_sub.save_subscriber()

    return redirect(url_for('main.profile',name=current_user.username))

  title='Profile'
  quote=get_quotes()
  return render_template('profile/profile.html',title=title,user=user,personalblogs=personalblogs,form=form,quote=quote)  

@main.route('/profile/<name>/update', methods=['GET','POST'])
def update_profile(name):
  '''
  view function that renders the update profile page form.
  '''
  user=User.query.filter_by(username=name).first()

  if user is None:
    abort(404)

  form=U_profileForm()
  if form.validate_on_submit():
    user.bio=form.bio.data  
    db.session.add(user)
    db.session.commit()

    return redirect(url_for('main.profile',name=user.username))

  return render_template('profile/update.html', form=form)  

@main.route('/profile/<name>/update/pic', methods=['GET','POST'])
@login_required
def update_pic(name):
  '''
  view function that pics the selected picture and saves it to the database as a path
  '''
  user=User.query.filter_by(username=name).first()
  
  if 'photo' in request.files:
    filename=photos.save(request.files['photo'])
    path=f'photos/{filename}'
    user.profile_pic_path=path
    db.session.commit()

  return redirect(url_for('main.profile', name=user.username))  

@main.route('/blog/comments/<int:id>', methods=['GET','POST'])
@login_required
def comments(id):
  '''
  view function that render comment template containing comments for a blog
  '''
  form=commentForm()
  blog_Com=Blog.query.filter_by(id=id).first()
  blog_by=blog_Com.posted_by

  if form.validate_on_submit():
    body=form.body.data

    new_comment=Comment(body=body,posted_by=current_user.username,blog_id=id)

    new_comment.save_comment()

    return redirect(url_for('.comments',id=id))


  title="Comments"
  comments=Comment.get_comments(id)

  return render_template('comments.html',title=title,comments=comments,form=form,blog_by=blog_by)

@main.route('/delComment/<int:id>')
@login_required
def delComment(id):
  '''
  view function that deletes a comment if only the comment belongs to the current user
  '''
  
  comment=Comment.query.filter_by(id=id).first()

  comment.delete_comment()

  return redirect(url_for('main.comments',id=comment.blog_id))

@main.route('/delBlog/<int:id>')
@login_required
def delBlog(id):
  '''
  view function that deletes a blog if only the blog belog belongs to the current user
  '''
  
  blog_del=Blog.query.filter_by(id=id).first()

  blog_del.delete_blog()

  return redirect(url_for('main.blog',category=blog_del.category))

blog/templates/base.html
<!DOCTYPE html>
{% extends 'bootstrap/base.html' %}
<html>
<head>
  <meta charset="utf-8">
  {% if title %}
  <title>{{title}}</title>
  {% else %}
  <title>Blog_Site</title>
  {% endif %}  

</head>
<body>

  {% block navbar %}
    {% include 'navbar.html' %}  
  {% endblock navbar %}


  {% block styles %}
    {{super()}}
    {{simplemde.css}}
    {{simplemde.js}}
    <link rel="stylesheet" type="text/css" href="{{url_for('static',filename='css/base.css')}}">
    <link href="https://fonts.googleapis.com/css?family=Gupter&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Abril+Fatface|Akronim|Fredericka+the+Great&display=swap" rel="stylesheet">
  {% endblock styles %}
      
  {% block content %}
  {% endblock content %}
    
</body>
</html>

blog/templates/blog.html
{% extends 'base.html' %}

{% block styles %}
  {{super()}}
  <link rel="stylesheet" type="text/css" href="{{url_for('static',filename='css/blog.css')}}">
{% endblock styles %}

{% block content %}
  <h1 class="jumbotron">{{title}}</h1>  
  <div class="container">
    <div class="row">
      <div class="col-md-2">
        <div class="dropdown">          
          <a class="nav-link btn btn-warning" href="/blog/Lifestyle Blogs">Lifestyle Blogs</a><br>
          <a class="nav-link btn btn-warning" href="/blog/Entertainment Blogs">Entertainment Blogs</a><br>
          <a class="nav-link btn btn-warning" href="/blog/Education Blogs">Education Blogs</a><br>
          <a class="nav-link btn btn-warning" href="/blog/Political Blogs">Political Blogs</a><br>
          <a class="nav-link btn btn-warning" href="/blog/Fashion Blogs">Fashion Blogs</a><br>  

          {% if current_user.is_authenticated %}
            <a class="btn btn-outline-info" href="{{url_for('main.new_blog')}}">Post a Blog</a>
          {% else %}  
            <a class="btn btn-outline-info" href="{{url_for('auth.signin')}}">Sign in to post</a>
          {% endif %}     
        </div>
      </div>
      <div class="col-md-10">
          {% if blogs %}

            {% for blog in blogs %}
              <div style="margin-left:10px" class="card bg-dark">
                <div style="color:lightblue" class="card-header"><b>Title: {{blog.title}}</b></div>
                <div style="color:lightblue" class="card-body">{{blog.body|safe}}</div>
                <div class="card-footer">
                  <ul>              
                    <li class="card-text"><small class="text-muted">Posted On: {{blog.posted_on.strftime('%Y-%m-%d')}}</small></li>              
                    <li class="card-text"><small class="text-muted">Posted By: {{blog.posted_by}}</small></li>                          
                  </ul>
                  {% if current_user.is_authenticated %}
                    <a class="btn btn-success" href="{{url_for('main.comments',id=blog.id)}}">View Comments</a>
                  {% else %}  
                    <a class="btn btn-success" href="{{url_for('auth.signin')}}">Sign in to View Comments</a>
                  {% endif %}  
                </div>

                <div>
                {% if blog.posted_by==current_user.username %}
                  <a class="btn btn-outline-primary" href="{{url_for('main.update_blog',id=blog.id)}}">Update Blog</a>
                  <a class="btn btn-outline-danger" href="{{url_for('main.delBlog',id=blog.id)}}">Delete Blog</a>
                {% endif %}  
                </div>            
              </div>    
              <br>         
            {% endfor %}

          {% else %}  
            <h4 class="alert alert-danger">There are No Blogs for this category!</h4>
          {% endif %}  
      </div>
    </div>
  </div>
  
{% endblock content %}

blog/templates/comments.html
{% extends 'base.html' %}

{% import 'bootstrap/wtf.html' as wtf %}


{% block styles %}
  {{super()}}
  <link rel="stylesheet" type="text/css" href="{{url_for('static',filename='css/comment.css')}}">
{% endblock styles %}

{% block content %}
  <h1 class="jumbotron">Comments</h1>
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-6">
      {% if comments %}

        {% for comment in comments %}
          <div class="card">
            <h5 class="card-header">{{comment.body}}</h5>
            <div class="body">
              <p class="card-text"><small class="text-muted">Posted On: {{comment.posted_on.strftime('%Y-%m-%d')}}</small></p>              
              <p class="card-text"><small class="text-muted">Posted By: {{comment.posted_by}}</small></p>                                             
            </div>     

            {% if blog_by==current_user.username %}       
              <a class="btn btn-outline-danger" href="{{url_for('main.delComment',id=comment.id)}}">Delete</a>                          
            {% elif comment.posted_by==current_user.username %}        
              <a class="btn btn-outline-danger" href="{{url_for('main.delComment',id=comment.id)}}">Delete</a>                          
            {% endif %}      

          </div>
          <br>
        {% endfor %}  
      {% else %}
        <h5 class="alert alert-danger">There are no comments for this Blog</h5>
      {% endif %}

      
      </div>

      <div style="color:white" class="col-md-6">
        {{wtf.quick_form(form)}}
      </div>
      
    </div>
  </div>


{% endblock content %}

blog/templates/errorFour.html
{% extends 'base.html' %}

{% block content %}
<h1 class="jumbotron">Page Note Found</h1>
<p>The page your looking for wasn't found.</p>
<a class="btn btn-outline-danger" href="/">Home</a>
{% endblock content %}

blog/templates/index.html
{% extends 'base.html' %}

{% block styles %}
  {{super()}}
  <link rel="stylesheet" type="text/css" href="{{url_for('static',filename='css/index.css')}}">
{% endblock styles %}

{% block content %}
  <div class="container-fluid">    
    <h1 class="jumbotron">Welcome to Blog Post</h1>
    <div class="row">
        <div class="col"><a href="/blog/Lifestyle Blogs">
          <h3 style="color:lightblue">Lifestyle Blogs</h3>
          <div class="flip-box">
            <div class="flip-box-inner">
              <div class="flip-box-front">
                <img src="https://howto.co.ke/wp-content/uploads/2019/01/41820514-lifestyle-word-cloud-fitness-sport-health-concept.jpg" width="250px" height="200px">
              </div>
              <div class="flip-box-back">
                <h3>Lifestyle Blogs</h3>
                <p>Get to read Blogs from bloggers whose blogs revolve around our Social lives</p>
              </div>
            </div>
          </div>
          </a>
        </div>  

        <div class="col"><a href="/blog/Entertainment Blogs">
          <h3 style="color:lightblue">Entertainment Blogs</h3>
          <div class="flip-box">
            <div class="flip-box-inner">
              <div class="flip-box-front">
                <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR4rY-7nrIe_ZMFGsW_tlxN1KK7iMC2eMuES-HZiX9SCos5IXks&s" width="250px" height="200px">
              </div>
              <div class="flip-box-back">
                <h3>Entertainment Blogs</h3>
                <p>Get to read Blogs from bloggers whose blogs revolve the entertainment section</p>
              </div>
            </div>
          </div>
          </a>
        </div>  

        <div class="col"><a href="/blog/Religious Blogs">
          <h3 style="color:lightblue">Religious Blogs</h3>
          <div class="flip-box">
            <div class="flip-box-inner">
              <div class="flip-box-front">
                <img src="https://www.history.com/.image/ar_16:9%2Cc_fill%2Ccs_srgb%2Cfl_progressive%2Cg_faces:center%2Cq_auto:good%2Cw_768/MTY3NDcyMDYwNzAyOTI2NjM3/christianity-gettyimages-121153575.jpg" width="250px" height="200px">
              </div>
              <div class="flip-box-back">
                <h3>Religious Blogs</h3>
                <p>Get to read Blogs from bloggers whose blogs revolve the various types of religions</p>
              </div>
            </div>
          </div>
          </a>
        </div>  

        <div class="col"><a href="/blog/Education Blogs">
          <h3 style="color:lightblue">Education Blogs</h3>
          <div class="flip-box">
            <div class="flip-box-inner">
              <div class="flip-box-front">
                <img src="http://www.standardmedia.co.ke/images/friday/thumb_education_critical_t5cdf1649a3372.jpg" width="250px" height="200px">
              </div>
              <div class="flip-box-back">
                <h3>Education Blogs</h3>
                <p>Get to read Blogs from bloggers whose blogs revolve the education sector</p>
              </div>
            </div>
          </div>
          </a>
        </div>  

        <div class="col"><a href="/blog/Political Blogs">
          <h3 style="color:lightblue">Political Blogs</h3>
          <div class="flip-box">
            <div class="flip-box-inner">
              <div class="flip-box-front">
                <img src="https://www.voicesofyouth.org/sites/default/files/images/2019-01/politics3.jpg" width="250px" height="200px">
              </div>
              <div class="flip-box-back">
                <h3>Political Blogs</h3>
                <p>Get to read Blogs from bloggers whose blogs revolve the politics sector</p>
              </div>
            </div>
          </div>
          </a>
        </div>  

        <div class="col"><a href="/blog/Fashion Blogs">
          <h3 style="color:lightblue">Fashion Blogs</h3>
          <div class="flip-box">
            <div class="flip-box-inner">
              <div class="flip-box-front">
                <img src="https://us.123rf.com/450wm/dizanna/dizanna1906/dizanna190600016/124399956-stock-vector-fashion-word-cloud-collage-concept-background.jpg?ver=6" width="250px" height="200px">
              </div>
              <div class="flip-box-back">
                <h3>fashion Blogs</h3>
                <p>Get to read Blogs from bloggers whose blogs revolve the fashion ans style</p>
              </div>
            </div>
          </div>
          </a>
        </div>  

    </div>
    <br>
    <h1 style="color:gold" class="text-center">Quote per Minute</h1>
    {% for quote in quote %}
      <div style="color:lightblue" class="card bg-transparent">
        <p class="text-center">{{quote.quote}}</p>
        <p class="text-center"><small>Author: {{quote.author}}</small></p>
      </div>
    {% endfor %}              
  </div>
  <div class="social">
      <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSIAYlfY2Qgz-1Mtn2GoH8gSYguLSlHsGNjWljRd9E_f-10Jj4B&s" style="border-radius: 360%" width="100px" height="100px" alt="facebook"> <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRqbrHXPllF6IRseJbxbvwyvOz34DaZiq_sX2i8eCbDOdo5-ObC&s" style="border-radius: 360%" width="100px" height="100px" alt="twitter"> <img src="https://icon-library.net/images/instagram-icon-black-and-white-png/instagram-icon-black-and-white-png-2.jpg" style="border-radius: 360%" width="100px" height="100px" alt="instagram"> <img src="https://www.clipartwiki.com/clipimg/detail/257-2577470_email-icons-clipart-mail-black-icon-png.png" style="border-radius: 360%" width="100px" height="100px" alt="email"> <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFdqNTKmxXfA5XDUK6oEY6dkstPScrcDgGi5c9IEe9k0S8Et7f&s" style="border-radius: 360%" width="100px" height="100px" alt="telephone"> 
      <h6 style="color:gold">BLOG POST <br>
            2019
      </h6>
  </div>
{% endblock content %}

blog/templates/navbar.html
  <nav class="navbar sticky-top navbar-expand-lg navbar-light bg-transparent btn-outline-info">
    <a class="navbar-brand" href="/"><img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSLr2bma3X7VaUW1vgxIVIuVUvcOBbylTrSSOsrt47WKws3v46Wyw&s" witch="60px" height="50px"alt=""></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link btn btn-warning" style="color:black" href="/">Home <span class="sr-only">(current)</span></a>
        </li>            

        <li class="nav-item">
            <a class="nav-link"></a>
          </li>                       

        <div class="dropdown">
          <button class="nav-link btn btn-info dropdown-toggle" style="color:black" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Types of Blogs</button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a class="nav-link btn btn-outline-info" href="/blog/Lifestyle Blogs">Lifestyle Blogs</a>
            <a class="nav-link btn btn-outline-info" href="/blog/Entertainment Blogs">Entertainment Blogs</a>
            <a class="nav-link btn btn-outline-info" href="/blog/Education Blogs">Education Blogs</a>
            <a class="nav-link btn btn-outline-info" href="/blog/Political Blogs">Political Blogs</a>
            <a class="nav-link btn btn-outline-info" href="/blog/Fashion Blogs">Fashion Blogs</a>
          </div>
        </div>

      </ul>
      <ul class="navbar-nav ml-auto">  
        {% if current_user.is_authenticated %}   
          
          <button class="nav-link btn btn-danger dropdown-toggle" style="color:black" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{current_user.username}}</button>
          <div style="margin-left:85%" class="dropdown-menu" aria-labelledby="dropdownMenuButton">            
            <a class="btn btn-outline-danger" href="{{url_for('main.profile',name=current_user.username)}}">Profile</a>
            <a class="nav-link"></a>
            <a class="btn btn-outline-danger" href="{{url_for('auth.signout')}}">Sign out</a>
          </div>
    
        {% else %}
          <li class="nav-item">
            <a class="btn btn-outline-danger" href="{{url_for('auth.signin')}}">Sign in</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </nav>

blog/templates/new_blog.html
{% extends 'base.html' %}

{% import 'bootstrap/wtf.html' as wtf %}

{% block styles %}
  {{super()}}
  <link rel="stylesheet" type="text/css" href="{{url_for('static',filename='css/forms.css')}}">
{% endblock styles %}

{% block content %}
  <div class="container-fluid">
    <h1 class="jumbotron">New Blog</h1>
    
      {{wtf.quick_form(form)}}
      {{simplemde.load}}    
      
  </div>

{% endblock content %}

blog/templates/profile/profile.html
{% extends 'base.html' %}

{% import 'bootstrap/wtf.html' as wtf %}

{% block styles %}
  {{super()}}
  <link rel="stylesheet" type="text/css" href="{{url_for('static',filename='css/profile.css')}}">
{% endblock styles %}


{% block content %}
<div class="container">
  <h1 class="jumbotron">Profile page for {{user.username}}</h1>
  <div class="row">
  <div class="col-md-5">
    {% if user.profile_pic_path %}
      <img class="card" src="{{url_for('static',filename=user.profile_pic_path)}}" alt="Profile Pic" class="img-thumbnail" width="250px" height="250px">
    {% else %}  
      <h6 class="alert alert-danger">No profile pic</h6>
    {% endif %}  
    
    {% if user==current_user %}
    <form action="{{url_for('main.update_pic',name=user.username)}}" method="post" enctype="multipart/form-data">
      <input type="file" name="photo" class="form-control" required>

      <input class="btn btn-success" type="submit">
    </form>  
    {% endif %}
    <h3>Name: {{user.username}}</h3>
    <h3>Bio:</h3>
    {% if user.bio %}
      <h4>{{user.bio}}</h4>
    {% else %}  
      <h6 class="alert alert-danger">{{user.username}} has no bio</h6>
      <br>
    {% endif %}
    <a class="btn btn-outline-info" href="{{url_for('main.update_profile',name=user.username)}}">Edit Bio</a>
    <br>
    <hr>
    <button class="nav-link btn btn-info dropdown-toggle" style="color:black" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Subscribe to Blog Post web app</button>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">            
        {{wtf.quick_form(form)}}
      </div>
    <hr>
    <h5 style="color:gold" class="text-center">Quote per Minute</h5>
    {% for quote in quote %}
      <div class="card">
        <h6>{{quote.quote}}</h6>
        <h6><small>Author: {{quote.author}}</small></h6>
      </div>
    {% endfor %}     

  </div>
  <div class="col-md-7">
    <h2><b><u>My Blogs</u></b></h2>
    {% if personalblogs %}
      {% for blog in personalblogs %}
        <div class="card bg-dark">
          <h5 style="color:lightblue"><b>Title: {{blog.title}}</b></h5>
          <h6 style="color:lightblue"><b><i>{{blog.body|safe}}</i></b></H6>
          <h6 style="color:lightblue">Category :{{blog.category}}</h6>
          <h6 class="card-text"><small class="text-muted">Posted On: {{blog.posted_on.strftime('%Y-%m-%d')}}</small></h6>              
          <h6 class="card-text"><small class="text-muted">Posted By: {{blog.posted_by}}</small></h6>   

          <div class="text-center">
            <a class="btn btn-success" href="{{url_for('main.comments',id=blog.id)}}">View Comments</a>            
            {% if blog.posted_by==current_user.username %}
            <a class="btn btn-outline-danger" href="{{url_for('main.delBlog',id=blog.id)}}">Delete Blog</a>
            {% endif %}              
          </div>                       
        </div>
        <br>                          
        {% endfor %}
    {% else %}    
      <h6 class="alert alert-danger">You have no Blogs {{user.username}}</h6>
    {% endif %}  
    
  </div>
</div>
{% endblock content %}

blog/templates/profile/update.html
{% extends 'base.html' %}

{% import 'bootstrap/wtf.html' as wtf %}

{% block styles %}
  {{super()}}
  <link rel="stylesheet" type="text/css" href="{{url_for('static',filename='css/forms.css')}}">
{% endblock styles %}


{% block content %}

  <div class="container-fluid">
  <h1 class="jumbotron">Update Bio</h1>
    <div class="row">
      <div class="col-md-3"></div>
      <div class="col-md-6">
        {{wtf.quick_form(form)}}
      </div>
      <div class="col-md-3"></div>
    </div>
  </div>

{% endblock content %}

blog/templates/updateblog.html
{% extends 'base.html' %}

{% import 'bootstrap/wtf.html' as wtf %}

{% block styles %}
  {{super()}}
  <link rel="stylesheet" type="text/css" href="{{url_for('static',filename='css/forms.css')}}">
{% endblock styles %}

{% block content %}

  <h1 class="jumbotron">Update Blog</h1>
  <div class="container">    
    {{wtf.quick_form(form)}}
    {{simplemde.load}}    
  </div>

{% endblock content %}